name: rayzi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  convex_bottom_bar: ^3.1.0+1
  carousel_slider:
  bottom_picker: ^2.0.0
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.6
  video_player: ^2.4.7
  lottie: ^1.4.3
  camera: ^0.10.4
  fluttertoast: ^8.1.3
  like_button: ^2.0.5
#  flutter_inapp_purchase: ^5.3.1
#  collection: ^1.16.0
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  platform_device_id: ^1.0.1
  agora_rtc_engine: ^5.3.1
  socket_io_client: ^2.0.0
  just_audio: ^0.9.11
  record: ^3.0.0
  font_awesome_flutter: ^9.1.0
  flutter_vibrate: ^1.1.0
  flutter_local_notifications: ^13.0.0
#  in_app_purchase: ^3.1.5
  razorpay_flutter: ^1.3.4
  flutter_stripe: ^8.0.0+1
  cached_network_image: ^3.2.3
  flutter_branch_sdk: ^6.6.0
  share_plus: any
  flutter_inappwebview: ^5.7.2+3
  firebase_crashlytics: ^3.1.1


  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: abold
      fonts:
        - asset: Font/abold.OTF
    - family: alight
      fonts:
        - asset: Font/alight.OTF
    - family: amidum
      fonts:
        - asset: Font/amidum.OTF
    - family: pacifico
      fonts:
        - asset: Font/pacifico.ttf
    - family: aregular
      fonts:
        - asset: Font/aregular.OTF
    - family: AvenirNextLTPro-Demi
      fonts:
        - asset: Font/AvenirNextLTPro-Demi.otf

  assets:
    - lottie/
    - Images/
    - Images/Home/
    - Images/Message/
    - Images/Center_Tab/
    - Images/Profile/
    - Images/Post_Screen/
    - Images/User_Profile/
    - Images/Video/
    - Images/Gift/
    - Images/new_dis/
    - Images/Gender/B&W/
    - Images/Gender/Color/
    - Images/IconsImage/
    - assets/
    - assets/gpay.json
    - audio/call.mp3

